[project]
name = "app-runner-fastapi-sample"
version = "1.0.0"
description = "FastAPI application for AWS App Runner"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
]
requires-python = ">=3.11"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "httpx>=0.24.0",
]